name: Build MeloNX iOS (IPA)

on:
  push:
    branches: [ "main" ] 
  workflow_dispatch:     

jobs:
  build_ipa:
    runs-on: macos-14 

    steps:
      - name: Lấy Source Code
        uses: actions/checkout@v4

      - name: Cài đặt .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Chạy Script Build iOS của Dev cũ
        run: |
          chmod +x distribution/ios/*.sh
          ./distribution/ios/compile.sh 

      - name: Lấy file IPA mang về
        uses: actions/upload-artifact@v4
        with:
          name: MeloNX-iOS-Release
          path: "**/*.ipa"